import "./globals.css";
import { Inter } from "next/font/google";

import AuthContext from "./context/AuthContext";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="icon" href="/login/logo.svg" />
      </head>
      <body>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}
